### ISSUE TITLE
To add more pages

### ISSUE THREAD

**Issue by monavariyas** [raahulahlawat/Docsify#3]
Why we are using vim here?

**Comment by raahulahlawat** [comment]
I apologize for mentioning Vim specifically in the previous response about Docsify setup. While Vim is a powerful text editor popular in the Linux community, it wasn't necessarily the intended recommendation for Docsify.

The suggestion was to use any basic text editor, and Vim was mentioned as an example alongside nano (another common Linux text editor) to provide options for Linux users.
